services:
  # 1. FastAPI API server service
  api:
    build:
      context: . # Use the Dockerfile in the project root
    container_name: gestaltmatcher-api
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s

  # 2. Nginx reverse proxy service
  nginx:
    build:
      context: ./nginx
    container_name: gestaltmatcher-proxy
    ports:
      - "443:443"
    volumes:
      - nginx_certs:/etc/ssl
    depends_on:
      api:
        condition: service_healthy
    # --- Add the following command to explicitly run the script and then nginx ---
    command: >
      sh -c "/docker-entrypoint.d/confirm-startup.sh && nginx -g 'daemon off;'"

# Define the named volume for persisting certificates
volumes:
  nginx_certs:
