/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Analysis: typeof import('./components/Analysis.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Export: typeof import('./components/Export.vue')['default']
    Results: typeof import('./components/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/Settings.vue')['default']
    Start: typeof import('./components/Start.vue')['default']
  }
}
